name: Nuclei Deep Scan - All Templates

on:
  workflow_dispatch:

jobs:
  nuclei:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Nuclei & Update Templates
        run: |
          echo "[*] Installing Nuclei via Go..."
          echo "GOPATH=$HOME/go" >> $GITHUB_ENV
          echo "PATH=$HOME/go/bin:$PATH" >> $GITHUB_ENV

          go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest

          echo "[*] Updating templates..."
          $HOME/go/bin/nuclei --update-templates

      - name: Run Nuclei on livesubs.txt
        run: |
          mkdir -p output
          echo "[*] Running nuclei scan on livesubs.txt..."
          $HOME/go/bin/nuclei -l livesubs.txt \
            -severity info,low,medium,high,critical \
            -o output/nuclei_deep_report.txt
          
          echo "[+] Scan complete."

      - name: Upload Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-deep-report
          path: output/nuclei_deep_report.txt

      - name: Notify Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "✅ Nuclei scan complete. Check GitHub Actions > Artifacts for full report."}' \
               https://discord.com/api/webhooks/1326843541078409318/Bl-ku08YLuUdYa9tomkfKtbf1zN_sxpFbCXaIz5hko3S86mbjnS3SfqYywKc56D0SRBY
