name: Nuclei Deep Scan - All Templates

on:
  workflow_dispatch:

jobs:
  nuclei:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Nuclei & Templates
        run: |
          go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
          nuclei --update-templates
        env:
          PATH: /home/runner/go/bin:${{ env.PATH }}

      - name: Run Nuclei Scan on livesubs.txt
        run: |
          mkdir -p output
          echo "[*] Running full Nuclei scan on livesubs.txt..."
          nuclei -l livesubs.txt \
            -t ~/nuclei-templates/ \
            -severity info,low,medium,high,critical \
            -o output/nuclei_deep_report.txt
          
          echo "[+] Scan complete. Output saved to output/nuclei_deep_report.txt"
        env:
          PATH: /home/runner/go/bin:${{ env.PATH }}

      - name: Upload Nuclei Results
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-deep-report
          path: output/nuclei_deep_report.txt

      - name: Notify Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "✅ Nuclei scan on livesubs.txt completed using all templates. Results are available in GitHub Actions → Artifacts."}' \
               https://discord.com/api/webhooks/1326843541078409318/Bl-ku08YLuUdYa9tomkfKtbf1zN_sxpFbCXaIz5hko3S86mbjnS3SfqYywKc56D0SRBY
